### PR TITLE
init: hello from back-end

### PR DESCRIPTION
**Pull request by Garongan**
woe minimal di init bro

### CODE REVIEW

**Comment by Garongan** [comment]
tolong di review lah, ayo lah, ayo lah

**Comment by irfans18** [comment]
Masih nyiapin requirement akhi

**Comment by irfans18** [comment]
Tambahin dependency
spring security
validation 
postgresql driver
spring web
lombok

**Comment by Garongan** [comment]
udah bang

**Comment by irfans18** [comment]
Oke. Ajib kamu bang

**Pull request merged**
